[phases.setup]
nixPkgs = ["nodePackages.pnpm"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"

